baseURL: "https://celendi.xyz"
title: Celendi
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

googleAnalytics: G-5T7Z27D6K1

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Team Celendi
  description: "Celendi is a multi-functional discord bot designed to be the only bot you need in your server, containing a wide selection of commands from fun to moderation, we have it all!"
  keywords: [Celendi, Discord Bot, Celendi Bot]
  author: Team Celendi
  # author: ["Me", "You"] # multiple authors
  images: ["celendibanner.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light, auto
  disableThemeToggle: true

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "Celendi_RED.png"
    favicon16x16: "Celendi_RED.png"
    favicon32x32: "Celendi_RED.png"
    apple_touch_icon: "Celendi_RED.png"
    safari_pinned_tab: "Celendi_RED.png"

  label:
    text: " "
    icon: celendibanner.png
    iconHeight: 50
  
  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Celendi
    subtitle: "Celendi is a multi-functional discord bot designed to be the only bot you need in your server, containing a wide selection of commands from fun to moderation, we have it all!"
    imageUrl: "https://static.celendi.xyz/img/Celendi_RED.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Celendi Logo
    buttons:
      - name: Invite
        url: https://discord.com/oauth2/authorize?client_id=786679486749999214&permissions=3207851399&scope=bot%20applications.commands
      - name: Discord
        url: https://discord.com/invite/YeGXPJWTbz

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: kofi
      url: "https://ko-fi.com/celendibot"
    - name: github
      url: "https://github.com/celendi"
    - name: facebook
      url: "https://www.facebook.com/celendibot"
    - name: instagram
      url: "https://instagram.com/celendibot" 
    - name: twitter
      url: "https://twitter.com/celendibot"
    - name: reddit
      url: "https://reddit.com/r/celendibot"
    - name: tiktok
      url: "https://tiktok.com/@celendibot"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/celendi/site/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: Invite
      name: Invite
      url: https://discord.com/oauth2/authorize?client_id=786679486749999214&permissions=3207851399&scope=bot%20applications.commands
      weight: 1
    - identifier: Discord
      name: Discord
      url: https://discord.gg/invite/YeGXPJWTbz
      weight: 2
    - identifier: Status
      name: Status
      url: https://status.celendi.xyz
      weight: 3
    - identifier: Documentation
      name: Documentation
      url: https://docs.celendi.xyz
      weight: 4

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true