baseURL: "https://celendi.xyz"
title: Celendi
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Celendi
  description: "Celendi is a multi-functional discord bot designed to be the only bot you need in your server, containing a wide selection of commands from fun to moderation, we have it all!"
  keywords: [Celendi, Discord Bot, Celendi Bot]
  author: Celendi
  # author: ["Me", "You"] # multiple authors
  images: ["https://raw.githubusercontent.com/Celendi/brand-kit/main/Logos/celendibanner.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light, auto
  disableThemeToggle: true

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "https://github.com/Celendi/brand-kit/blob/main/Logos/Bot%20Logos/Celendi_RED.png?raw=true"
    favicon16x16: "https://github.com/Celendi/brand-kit/blob/main/Logos/Bot%20Logos/Celendi_RED.png?raw=true"
    favicon32x32: "https://github.com/Celendi/brand-kit/blob/main/Logos/Bot%20Logos/Celendi_RED.png?raw=true"
    apple_touch_icon: "https://github.com/Celendi/brand-kit/blob/main/Logos/Bot%20Logos/Celendi_RED.png?raw=true"
    safari_pinned_tab: "https://github.com/Celendi/brand-kit/blob/main/Logos/Bot%20Logos/Celendi_RED.png?raw=true"

  label:
    text: " "
    icon: https://raw.githubusercontent.com/Celendi/brand-kit/main/Logos/celendibanner.png?raw=true
    iconHeight: 50

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Celendi
    subtitle: "Celendi is a multi-functional discord bot designed to be the only bot you need in your server, containing a wide selection of commands from fun to moderation, we have it all!"
    imageUrl: "https://github.com/Celendi/brand-kit/blob/main/Logos/Bot%20Logos/Celendi_RED.png?raw=true"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Celendi Logo
    buttons:
      - name: Invite
        url: https://discord.com/oauth2/authorize?client_id=786679486749999214&permissions=3207851399&scope=bot%20applications.commands
      - name: Support
        url: https://discord.com/invite/GWdnwwYMjZ

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: "https://twitter.com/celendibot"
    - name: github
      url: "https://github.com/celendi"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/celendi/site/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: Invite
      name: Invite
      url: https://discord.com/oauth2/authorize?client_id=786679486749999214&permissions=3207851399&scope=bot%20applications.commands
      weight: 10
    - identifier: Support
      name: Support
      url: https://discord.gg/invite/YeGXPJWTbz
      weight: 20
    - identifier: Documentation
      name: Documentation
      url: https://docs.celendi.xyz
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
