baseURL: "https://celendi.gg"
title: Celendi
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

googleAnalytics:

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Team Celendi
  description: "Celendi is a multipurpose discord bot designed to be the only bot you need in your server, containing a wide selection of commands from fun to moderation, we have it all!"
  keywords: [Celendi, Discord Bot, Celendi Bot]
  author: Team Celendi
  # author: ["Me", "You"] # multiple authors
  images: ["https://github.com/Celendi/Brand-Kit/blob/main/banners/transparant.png?raw=true"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light, auto
  disableThemeToggle: true

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "https://github.com/Celendi/Brand-Kit/blob/main/favicons/favicon.ico?raw=true"
    favicon16x16: "https://github.com/Celendi/Brand-Kit/blob/main/favicons/favicon-16x16.png?raw=true"
    favicon32x32: "https://github.com/Celendi/Brand-Kit/blob/main/favicons/favicon-32x32?raw=true"
    apple_touch_icon: "https://github.com/Celendi/Brand-Kit/blob/main/favicons/apple-touch-icon.png?raw=true"
    safari_pinned_tab: "https://github.com/Celendi/Brand-Kit/blob/main/favicons/favicon.ico?raw=true"

  label:
    text: " "
    icon: "https://github.com/Celendi/Brand-Kit/blob/main/banners/transparant.png?raw=true"
    iconHeight: 80
  
  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Celendi
    subtitle: "Celendi is a multipurpose discord bot designed to be the only bot you need in your server, containing a wide selection of commands from fun to moderation, we have it all!"
    imageUrl: "https://raw.githubusercontent.com/Celendi/Brand-Kit/main/logos/red/red.svg?raw=true"
    imageWidth: 200
    imageHeight: 200
    imageTitle: Celendi Logo
    buttons:
      - name: Invite
        url: https://celendi.gg/invite
      - name: Discord
        url: https://celendi.gg/discord

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: kofi
      url: "https://ko-fi.com/celendibot"
    - name: github
      url: "https://github.com/celendi"
    - name: twitter
      url: "https://twitter.com/celendibot"
    - name: reddit
      url: "https://reddit.com/r/celendibot"
    - name: tiktok
      url: "https://tiktok.com/@celendibot"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
    
menu:
  main:
    - identifier: Invite
      name: Invite
      url: https://celendi.gg/invite
      weight: 1
    - identifier: Vote
      name: Vote
      url: https://celendi.gg/vote
      weight: 2 
    - identifier: Discord
      name: Discord
      url: https://celendi.gg/discord
      weight: 3
    - identifier: Status
      name: Status
      url: https://status.celendi.gg
      weight: 4
    - identifier: Documentation
      name: Documentation
      url: https://docs.celendi.gg
      weight: 5
    

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
