name: Github Packages - Site Edition
on:
  push:
    branches:
      - 'dev'
  workflow_dispatch:
jobs:
  build:
   runs-on: ubuntu-latest
   permissions:
      packages: write
      contents: read
   steps:
    -
      name: Checkout 
      uses: actions/checkout@v2
    -
      name: Login to ghcr
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN}}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ghcr.io/celendi/site:development
        cache-from: type=gha
        cache-to: type=gha,mode=max
    -
      uses: sarisia/actions-status-discord@v1.9.0
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{ job.status }}
        title: "Build #${{ github.run_number }} of Celendi Site: ${{ job.status }}"
        description: "Build number #${{ github.run_number }} of Celendi Site is now available.\nThis is a dev build, and it might not be stable. [Download Build](https://github.com/Celendi/site/pkgs/container/site)"
        nodetail: true
        username: Celendi Build's
